# Generated by Django 4.2.1 on 2023-05-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uts', '0006_aktuator_2_aktuator_3_rename_aktuator_aktuator_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDataX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
