# Generated by Django 4.2.1 on 2023-05-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uts', '0007_sensordatax_delete_sensordata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SensorDataX',
            new_name='SensorData',
        ),
    ]
